name: Fetch and deploy updated player stats
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"
jobs:
  resources:
    name: Fetch stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18.12.0

      - name: Fetch stats
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY_ID: ${{ secrets.GOOGLE.PRIVATE_KEY_ID }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
        run: |
          echo $GOOGLE_CLIENT_ID
          yarn
          ./cron/run.sh

      - name: Deploy update
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            ./cron/data/players-new.json
            ./cron/data/players-old.json
            ./cron/data/timestamp.json
            ./cron/logs/log.txt
          commit-msg: Deploy updated stats
          github-token: ${{ secrets.GITHUB_TOKEN }}