name: Fetch and deploy updated player stats
on:
  workflow_dispatch:
jobs:
  resources:
    name: Fetch stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18.12.0

      - name: Fetch stats
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY_ID: ${{ secrets.GOOGLE_PRIVATE_KEY_ID }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
        run: |
          yarn
          ./cron/run.sh

      - name: Commit update
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            cron/data/players-new.json
            cron/data/players-old.json
            cron/data/timestamp.json
          commit-msg: Commit updated stats
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Deploy update
        run: |
          git config --global user.email "freemanb2@hotmail.com"
          git config --global user.name "Brandon Freeman"
          npm run --prefix "/home/runner/work/InSlippiLeaderboard/InSlippiLeaderboard" deploy